name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          version: 18
      - name: Install Dependencies & Build
        run: |
          npm ci 
          npm run build
      - name: Test
        run: npm test
